# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Loading My Settings
. ~/.dotfiles/zsh/funcs

. ~/.dotfiles/zsh/aliases

. ~/.dotfiles/zsh/paths

. ~/.dotfiles/zsh/plugins
